[package]
name = "monitr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive", "cargo"] }
home = "0.5.9"
serde_json = "1.0.133"
sysinfo = "0.32.1"
rusqlite = { version = "0.32.0", features = ["bundled"] }
chrono = "0.4.38"
